### ISSUE TITLE
PlatWin.cxx issues

### ISSUE THREAD

**Issue by MrMaxie** [t4th/win32-gui-wrapper#3]
Im not very familiar with C++ but I had two issues with file `PlatWin.cxx`, and I found how to solve them. But Im not sure why I had those issues.

1. First in 2801 line, my compiler can't resolve casting between `int` and `HMENU`, there was something about difference in sizes, so I changed this line into:
```
(HMENU)(UNIT_PTR)(UNIT)(ctrlID),
```
and well, it works right now.

2.  Next issues I had in lines 1538-1539. Compiler said something about wrong type of `x` and `y`, so I think it's some problem with name shadowing, because when I changed it into:
```
for (int y__=0; y__<height; y__++) {
    for (int x__=0; x__<width; x__++) {
        unsigned char *pixel = &image[0] + (y__*width+x__) * 4;
```
it works fine. 

Im on x64 Windows 10, using VS2019 with bundled C/C++ compiler from the same year.

PS Awesome job, people like me with problems with weird native GUI documentations can understand your code easly, because code of GUI using your library looks very clean and simple :3

**Comment by t4th** [comment]
Thank you for your kind words! For some reason github didn't set notification for my own repos...

PlatWin.cxx is part of Scintilla project which i used for thRichEdit control. 
I think you have used x64 compiler instead of x86 and all warnings enabled for this dll thus the issues.
